Repository FS05-PART3-TEAM2/5-fav_photo-team2-be, pull requests merged in 2025-03, with the labels that each got.

#6 Task: swagger 초기 설정
  package.json
  src/app.ts
  src/utils/swagger/swagger.ts
Labels: task

#10 최초 스키마 생성
  prisma/schema.prisma
  prisma/schema/auth.prisma
  prisma/schema/photo.prisma
  prisma/schema/user.prisma
Labels: help wanted

#30 feat: 교환 제안 취소/거절 PATCH API 구현
  src/domains/market/controllers/exchange.controller.ts
  src/domains/market/interfaces/exchange.interface.ts
  src/domains/market/market.routes.ts
  src/domains/market/services/exchange.service.ts
Labels: feature
